[package]
name = "crate-carbon"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]

[dependencies]
clap = "*"
cratedb = { git = "https://github.com/celaus/rust-cratedb" }
log4rs = { version = "*", features = ["serde_yaml"] }
log = "*"
mioco = "*"
